language: scala
scala:
  - 2.12.8

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot


before_script:
  - export TZ=Europe/Berlin

script:
  - sbt ++$TRAVIS_SCALA_VERSION "scripted"
