name: CI
on:
  pull_request:
jobs:
  ci-matrix:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 'openjdk@1.11' ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: sbt ci ${{ github.ref }}
        run: sbt ci
  ci:
    runs-on: ubuntu-24.04
    needs: [ci-matrix]
    steps:
      - name: Aggregate of lint, and all tests
        run: echo "ci passed"
