name: Release
on:
  push:
    branches: [ master ]
  release:
    types: [ published ]
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.11
      - name: Coursier cache
        uses: coursier/cache-action@v8
      - name: sbt ci-release ${{ github.ref }}
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
